#include "time.h"
#include "HeatSensor.h"
#include <stdlib.h>
#include "CalculationHelper.h"

HeatSensor::HeatSensor(int minTemprature, int maxTemprature, int tempratureSway, int lastTemperatureMeasured)
{
	SensorName = "HeatSensor";

	_minTemprature = minTemprature;
	_maxTemprature = maxTemprature;

	// Since we are faking data generated by a heat sensor - to make the tests believable, we limit how much consecutive tests vary from each other
	_tempratureSway = tempratureSway;

	if (_minTemprature >= _maxTemprature)
	{
		throw "HeatSensor recived minimum temprature that is bigger or equal than maximum remprature";
	}

	srand(time(NULL));
	_lastTemprature = lastTemperatureMeasured;
}

float HeatSensor::GenerateFakeSensorData()
{
	// ----- algorithem for sensor -----
	// 
	// addition or reduction from last temprature
	_currentTemprature = _lastTemprature + CalculationHelper::GetRandomNumber(-_tempratureSway, _tempratureSway); //use calculation helper for random
	
	// need to check if in range, and if not in range than will be at max or minimum
	if (_currentTemprature < _minTemprature)
	{
		_currentTemprature = _minTemprature;
	}
	else if (_currentTemprature > _maxTemprature)
	{
		_currentTemprature = _maxTemprature;
	}

	// change last temprature
	_lastTemprature = _currentTemprature;

	return _currentTemprature;
}